-- Add quality_score column to workbook_rows
ALTER TABLE public.workbook_rows 
ADD COLUMN IF NOT EXISTS quality_score INTEGER;

-- Update comment
COMMENT ON COLUMN public.workbook_rows.quality_score IS 'The 0-100 quality score generated by the content engine';
