// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgwocrvftiwxofvykmhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnd29jcnZmdGl3eG9mdnlrbWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTY3MDAsImV4cCI6MjA2NzU3MjcwMH0.FLxwNZ4i7gu_5-IUykJCPQMwSxPHMLuT-RAoF48Flo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});